// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK41HAnTIjmMzUQvN0Z3z2keSeQ_6W03o',
    appId: '1:244758788383:web:3d48e1eea50af14694182a',
    messagingSenderId: '244758788383',
    projectId: 'fir-auth-and-crud-flutter',
    authDomain: 'fir-auth-and-crud-flutter.firebaseapp.com',
    storageBucket: 'fir-auth-and-crud-flutter.appspot.com',
    measurementId: 'G-T1WZ0XGM15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQIUBWTfmtMM_mTb9E77If5PQOtmLDdk',
    appId: '1:244758788383:android:324232475e23711f94182a',
    messagingSenderId: '244758788383',
    projectId: 'fir-auth-and-crud-flutter',
    storageBucket: 'fir-auth-and-crud-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKfu4hFwdvczk8aiFFeA_afnf6gSNK6E4',
    appId: '1:244758788383:ios:31364e6d9882494e94182a',
    messagingSenderId: '244758788383',
    projectId: 'fir-auth-and-crud-flutter',
    storageBucket: 'fir-auth-and-crud-flutter.appspot.com',
    iosBundleId: 'com.example.firebaseAuthAndCrudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKfu4hFwdvczk8aiFFeA_afnf6gSNK6E4',
    appId: '1:244758788383:ios:bc3ce2e9e12ec71d94182a',
    messagingSenderId: '244758788383',
    projectId: 'fir-auth-and-crud-flutter',
    storageBucket: 'fir-auth-and-crud-flutter.appspot.com',
    iosBundleId: 'com.example.firebaseAuthAndCrudFlutter.RunnerTests',
  );
}
